name: on_push

on:
  push:
    branch:
      - '**' # This will run on all branches, and must be quoted to be handled by this yaml

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
